import {Roboto} from 'next/font/google'
import Nav from "../components/Nav"
export const metadata = {
  title: 'facusa.js',
  description: 'Generated by facusa.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >

      <Nav  />


        {children}</body>
    </html>
  )
}
